package com.fbart.research.dao;

import com.fbart.research.domain.StuEntity;

import java.util.List;

public interface StuEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stu
     *
     * @mbggenerated
     */
    int insert(StuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stu
     *
     * @mbggenerated
     */
    int insertSelective(StuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stu
     *
     * @mbggenerated
     */
    StuEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_stu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StuEntity record);

    int batchUpdate(List<StuEntity> mas);
}